name: C GoogleTest and Coverage

on:
  push:
    branches: [ "main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake g++ gcovr

    - name: Configure CMake
      run: |
        mkdir -p "演習13/build"
        cd "演習13/build"
        cmake ..

    - name: Build
      run: |
        cd "演習13/build"
        make

    - name: Run Tests
      run: |
        cd "演習13/build"
        ./test_exe  
      
    - name: Generate Coverage Report
      run: |
        cd "演習13/build"
        gcovr -r .. --print-summary >> $GITHUB_STEP_SUMMARY
        gcovr -r .. --html-details -o coverage.html

    - name: Upload Coverage Report
      uses: actions/checkout@v4
      with:
        name: coverage-report
        path: "演習13/build/coverage.html"